export const tenantsData = [
  {
    name: "Mubarak Muhammad",
    email: "mubarak.muhammad@example.com",
    createdAt: new Date("2021-08-01"),
    isActive: true,
    dataUsage: 120,
    subscription: "Premium",
    billingCycle: "Monthly",
  },
  {
    name: "Hafiz Muhammad",
    email: "hafiz.muhammad@example.com",
    createdAt: new Date("2022-02-14"),
    isActive: false,
    dataUsage: 85,
    subscription: "Standard",
    billingCycle: "Yearly",
  },
  {
    name: "Fatima Muhammad",
    email: "fatima.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 150,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    name: "Abida Muhammad",
    email: "abida.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 95,
    subscription: "Basic",
    billingCycle: "Quarterly",
  },
  {
    name: "Jamila Muhammad",
    email: "jamila.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 110,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
  {
    name: "Hafsah Muhammad",
    email: "hafsah.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 60,
    subscription: "Basic",
    billingCycle: "Monthly",
  },
  {
    name: "Azizatu Muhammad",
    email: "azizatu.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: false,
    dataUsage: 40,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    name: "Linda Taylor",
    email: "linda.taylor@example.com",
    createdAt: new Date("2022-03-10"),
    isActive: true,
    dataUsage: 130,
    subscription: "Enterprise",
    billingCycle: "Yearly",
  },
  {
    name: "Robert Anderson",
    email: "robert.anderson@example.com",
    createdAt: new Date("2021-09-01"),
    isActive: true,
    dataUsage: 200,
    subscription: "Premium",
    billingCycle: "Monthly",
  },
  {
    name: "Maria Thomas",
    email: "maria.thomas@example.com",
    createdAt: new Date("2020-01-15"),
    isActive: false,
    dataUsage: 55,
    subscription: "Basic",
    billingCycle: "Quarterly",
  },
  {
    name: "William Jackson",
    email: "william.jackson@example.com",
    createdAt: new Date("2021-11-25"),
    isActive: true,
    dataUsage: 170,
    subscription: "Standard",
    billingCycle: "Yearly",
  },
  {
    name: "Elizabeth Harris",
    email: "elizabeth.harris@example.com",
    createdAt: new Date("2023-01-05"),
    isActive: true,
    dataUsage: 140,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    name: "Christopher Martin",
    email: "christopher.martin@example.com",
    createdAt: new Date("2022-10-11"),
    isActive: true,
    dataUsage: 190,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
  {
    name: "Patricia Lee",
    email: "patricia.lee@example.com",
    createdAt: new Date("2021-02-08"),
    isActive: false,
    dataUsage: 65,
    subscription: "Basic",
    billingCycle: "Monthly",
  },
  {
    name: "Daniel Walker",
    email: "daniel.walker@example.com",
    createdAt: new Date("2023-03-18"),
    isActive: true,
    dataUsage: 125,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    name: "Nancy Hall",
    email: "nancy.hall@example.com",
    createdAt: new Date("2021-07-30"),
    isActive: false,
    dataUsage: 30,
    subscription: "Basic",
    billingCycle: "Yearly",
  },
  {
    name: "Mark Allen",
    email: "mark.allen@example.com",
    createdAt: new Date("2020-05-12"),
    isActive: true,
    dataUsage: 220,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    name: "Susan Young",
    email: "susan.young@example.com",
    createdAt: new Date("2022-11-22"),
    isActive: false,
    dataUsage: 75,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    name: "Joseph King",
    email: "joseph.king@example.com",
    createdAt: new Date("2023-02-28"),
    isActive: true,
    dataUsage: 180,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
  {
    name: "Karen Wright",
    email: "karen.wright@example.com",
    createdAt: new Date("2023-04-07"),
    isActive: false,
    dataUsage: 50,
    subscription: "Basic",
    billingCycle: "Monthly",
  },
  {
    name: "Steven Scott",
    email: "steven.scott@example.com",
    createdAt: new Date("2022-05-13"),
    isActive: true,
    dataUsage: 145,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    name: "Mubarak Muhammad",
    email: "mubarak.muhammad@example.com",
    createdAt: new Date("2021-08-01"),
    isActive: true,
    dataUsage: 120,
    subscription: "Premium",
    billingCycle: "Monthly",
  },
  {
    name: "Hafiz Muhammad",
    email: "hafiz.muhammad@example.com",
    createdAt: new Date("2022-02-14"),
    isActive: false,
    dataUsage: 85,
    subscription: "Standard",
    billingCycle: "Yearly",
  },
  {
    name: "Fatima Muhammad",
    email: "fatima.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 150,
    subscription: "Enterprise",
    billingCycle: "Monthly",
  },
  {
    name: "Abida Muhammad",
    email: "abida.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 95,
    subscription: "Basic",
    billingCycle: "Quarterly",
  },
  {
    name: "Jamila Muhammad",
    email: "jamila.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 110,
    subscription: "Premium",
    billingCycle: "Yearly",
  },
  {
    name: "Hafsah Muhammad",
    email: "hafsah.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: true,
    dataUsage: 60,
    subscription: "Basic",
    billingCycle: "Monthly",
  },
  {
    name: "Azizatu Muhammad",
    email: "azizatu.muhammad@example.com",
    createdAt: new Date("2023-06-21"),
    isActive: false,
    dataUsage: 40,
    subscription: "Standard",
    billingCycle: "Quarterly",
  },
  {
    name: "Linda Taylor",
    email: "linda.taylor@example.com",
    createdAt: new Date("2022-03-10"),
    isActive: true,
    dataUsage: 130,
    subscription: "Enterprise",
    billingCycle: "Yearly",
  },
  {
    name: "Robert Anderson",
    email: "robert.anderson@example.com",
    createdAt: new Date("2021-09-01"),
    isActive: true,
    dataUsage: 200,
    subscription: "Premium",
    billingCycle: "Monthly",
  },
];
